---
title: "equity_and_consistency_vpd"
author: "Drew Walker"
date: "2022-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here)
library(redcapAPI)
library(lme4)
library(nlme)
library(sjPlot)
library(sjmisc)
library(patchwork)
library(sjlabelled)
redcap_api_url <- 'https://redcap.ctsi.ufl.edu/redcap/api/' 
#set options to allow us to access project files
#below is the token and urls
options(redcap_api_url)

APIToken <- read_csv("apitoken.csv", col_names = FALSE)
StreetlightDatabaseToken <- as.character(APIToken[1,1])

rcon <- redcapConnection(redcap_api_url, token = StreetlightDatabaseToken)

#successful complete exportation of entire dataset 
myData <- exportRecords(rcon, labels=FALSE)

```

## creating on census, visited, vpd variables

- unlike the census one, we should calculate this iteratively (every date has the VPD only up to that date )
```{r vpd-cum-avg}
on_census_days_pt <- myData %>%
  select(record_id,date=census_date) %>% 
  filter(!is.na((date))) 

visited_days_pt <- myData %>% 
  select(record_id,date) %>% 
  mutate(visited = 1) %>% 
  filter(!is.na(date))

patient_reach_df <- left_join(on_census_days_pt,visited_days_pt, by = c("record_id","date"))
patient_reach_df[is.na(patient_reach_df)] <- 0
patient_reach_df <- patient_reach_df %>% 
  mutate(new_census = as.factor(ifelse(date >="2022-11-14", 1, 0)))

per_patient_reach_pt_iterative_vpd1 <- patient_reach_df %>% 
  group_by(record_id) %>% 
  arrange(date) %>% 
  mutate(percent_visited_to_date = cumsum(visited)/seq_along(visited),
         on_census = 1,
         days_on_census = cumsum(on_census),
       low_percent = case_when(percent_visited_to_date < .50~ 1, TRUE ~0))


overall_patient_reach_by_date <- patient_reach_df %>% 
  group_by(date) %>% 
  summarize(percent_visited = mean(visited))


```

## Pt Descriptives 

```{r descriptives}
# Gender text preprocessing
myData$preferred_gender <- trimws(myData$preferred_gender, which = "both")
myData$sex_assigned_at_birth <- trimws(myData$sex_assigned_at_birth, which = "both")
myData$preferred_gender <- tolower(myData$preferred_gender)
myData$sex_assigned_at_birth <- tolower(myData$sex_assigned_at_birth)

SGLPatientsREDCap <- myData %>% 
  group_by(record_id) %>% 
  fill(preferred_gender,bday,deceased,discord_user,discord_invite_status) %>% 
  mutate(team_cancer = unclass(first(project_team___1)),
    team_cf = unclass(first(project_team___2)),
    team_transplant = unclass(first(project_team___3)),
    team_sicklecell = unclass(first(project_team___4)),
    team_autoimmune = unclass(first(project_team___5)),
    team_gi = unclass(first(project_team___6)),
    team_other = unclass(first(project_team___7)),
    predicted_project_team = first(predicted_project_team),
    sex_and_gender_difference = case_when(preferred_gender != sex_assigned_at_birth ~ "1", TRUE~"0")) %>% 
  pivot_longer(cols = starts_with("team_"),names_to = "project_team", values_to = "team_value", values_drop_na = TRUE) %>%
  dplyr::select(record_id,id,discord_user,discord_invite_status,bday,deceased,predicted_project_team,project_team,preferred_gender,sex_assigned_at_birth,vol_preferred_pronouns___1,vol_preferred_pronouns___2,vol_preferred_pronouns___3,team_value,status,date_of_death,ff) %>% 
  fill(discord_user,discord_invite_status,bday,deceased,predicted_project_team,project_team,preferred_gender,sex_assigned_at_birth,vol_preferred_pronouns___1,vol_preferred_pronouns___2,vol_preferred_pronouns___3,team_value,status,date_of_death,ff) %>% 
  filter(team_value == "2") %>% 
  distinct(record_id,project_team, .keep_all = TRUE)

today <- as.Date(Sys.Date())
intervalbday <- SGLPatientsREDCap$bday %--% today
SGLPatientsREDCap$age <- intervalbday
# Date since 

date_list <- as_tibble(per_patient_reach_pt_iterative_vpd1$date)
date_list$value <- as.Date(date_list$value)
unique_date_list <- date_list %>% 
  unique() %>% 
  select(date = value) %>%
  mutate(days_since_launch = as.numeric(difftime(date,first(date), units = "days")), 
         years_since_launch = as.numeric(difftime(date,first(date),date, units = "days")/365))

per_patient_reach_pt_iterative_vpd2 <- left_join(per_patient_reach_pt_iterative_vpd1,unique_date_list,by ="date")

per_patient_reach_pt_iterative_vpd <- left_join(per_patient_reach_pt_iterative_vpd2,SGLPatientsREDCap, by = "record_id") 
```


```{r visualizations-individual, eval=FALSE}
vpd_over_time <- ggplot(per_patient_reach_pt_iterative_vpd, aes(date, percent_visited_to_date,color = ff))+
  geom_point()
vpd_over_time

```

```{r visualizations-overalll}
daily_visit_pct <- ggplot(overall_patient_reach_by_date, aes(date, percent_visited))+
  geom_line()+
  geom_vline(xintercept = as.POSIXct(as.Date("2022-11-14")),
             color = "dark green", size = 2, linetype = "dashed")
daily_visit_pct

```

```{r overall-rdd-graph}
overall_patient_reach_by_date%>% 
  select(date, percent_visited) %>% 
  filter(date >= "2022-05-14") %>% 
  mutate(new_census = as.factor(ifelse(date >="2022-11-14", 1, 0))) %>% 
  ggplot(aes(date,percent_visited, color = new_census)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r eda}
cor.test(per_patient_reach_pt_iterative_vpd$days_on_census,per_patient_reach_pt_iterative_vpd$percent_visited_to_date)
```


## MLMs 

* To-dos: add number of volunteers as a control variable 

```{r percent-as-outcome}
library(lme4)
library(nlme)
per_pt_model_df <- per_patient_reach_pt_iterative_vpd %>% 
  filter(date >= "2022-05-14") %>% 
  mutate(ff_clean = case_when(ff =="Yes"~1,
                              TRUE~0))

# Descriptives: preferred_gender, project_team, ff
descriptives_percent_visited = lmer(percent_visited_to_date ~ preferred_gender + project_team + ff_clean + (1|record_id), data = per_pt_model_df, REML=FALSE)

# Effect of new census and days on census 
census_percent_visited = lmer(percent_visited_to_date ~ new_census + days_on_census + ff_clean + years_since_launch + (1|record_id), data = per_pt_model_df, REML=FALSE)

tab_model(descriptives_percent_visited, census_percent_visited, dv.labels = c("Model 1: Patient Descriptives","Model 2:New Census"), show.aic = TRUE, show.dev = TRUE)

```

```{r visited-as-outcome}
#Descriptives predicting whether or not pt was visited
# low_percent
descriptives_visit_bin = glmer(visited ~ preferred_gender + project_team + ff_clean + (1|record_id), data = per_pt_model_df, family=binomial("logit"))


# Effect of just new census and days on census
# low_percent
new_census_visit_bin = glmer(visited ~ new_census + days_on_census + ff_clean + years_since_launch + (1|record_id), data = per_pt_model_df, family=binomial("logit"))

tab_model(descriptives_visit_bin, new_census_visit_bin, dv.labels = c("Model 1: Patient Descriptives on chance of getting visited","Model 2:New Census on Chance of getting Visited"), show.aic = TRUE, show.dev = TRUE)

```
## Dates of no-shift, but census was run
"2022-12-13", 
